import { DataSource, Repository } from 'typeorm';
import { encryptText, decryptText } from '../../shared/crypto.js';
import { RegistrationQueueEntity } from '../../db/entities/index.js';
import type { RegistrationStatus } from '../../db/entities/registration-queue.entity.js';

export interface QueueAutoRegistrationInput {
  proxyUrl?: string | null;
  createdByUserId?: string | null;
  count?: number;
}

export class RegistrationService {
  private queueRepo: Repository<RegistrationQueueEntity>;

  constructor(private readonly ds: DataSource) {
    this.queueRepo = ds.getRepository(RegistrationQueueEntity);
  }

  /** Queue N auto-registration tasks. Credentials are generated by the worker. */
  async queueAutoRegistration(input: QueueAutoRegistrationInput): Promise<RegistrationQueueEntity[]> {
    const count = Math.min(Math.max(1, input.count ?? 1), 20);
    const tasks: RegistrationQueueEntity[] = [];
    for (let i = 0; i < count; i++) {
      const entity = this.queueRepo.create({
        email: '',
        encryptedPassword: '',
        desiredHandle: '',
        proxyUrl: input.proxyUrl ?? null,
        status: 'pending',
        createdByUserId: input.createdByUserId ?? null
      });
      tasks.push(await this.queueRepo.save(entity));
    }
    return tasks;
  }

  async getNextPending(): Promise<RegistrationQueueEntity | null> {
    return this.queueRepo.findOne({
      where: { status: 'pending' },
      order: { createdAt: 'ASC' }
    });
  }

  async getTaskById(id: string): Promise<RegistrationQueueEntity | null> {
    return this.queueRepo.findOne({ where: { id } });
  }

  async updateStatus(
    taskId: string,
    status: RegistrationStatus,
    data?: { errorMessage?: string; accountId?: string }
  ): Promise<RegistrationQueueEntity | null> {
    const task = await this.queueRepo.findOne({ where: { id: taskId } });
    if (!task) return null;
    task.status = status;
    if (data?.errorMessage !== undefined) task.errorMessage = data.errorMessage;
    if (data?.accountId !== undefined) task.accountId = data.accountId;
    return this.queueRepo.save(task);
  }

  async setGeneratedCredentials(
    taskId: string,
    email: string,
    password: string,
    desiredHandle: string
  ): Promise<RegistrationQueueEntity | null> {
    const task = await this.queueRepo.findOne({ where: { id: taskId } });
    if (!task) return null;
    task.email = email;
    task.encryptedPassword = encryptText(password);
    task.desiredHandle = desiredHandle;
    return this.queueRepo.save(task);
  }

  getPassword(task: { encryptedPassword: string }): string {
    return decryptText(task.encryptedPassword);
  }
}
